[package]
name = "pngme"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/lpaulic/pngme"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.0"
clap = { version = "4.3", features = ["derive"]}
